[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
asset_manager = "DZ7JPmWHWTePh2B98U3cPUJqcyCr7YGy7uWJUXWfZYHN"
balanced_dollar = "4XUbw35nyyCAr5ysvbGFUEs2vYafNW1tpNMkFTVvxJU8"
centralized_connection = "AfhGGH99rDWmbbmLeUJddT7rMxu7MDQ4GwWNrajz7Jz4"
xcall = "DSdPvAhnr4AT9a53gTk7U2UL6YFqhUxednEJeyXfEUve"
xcall_manager = "BLtyB6K2yu942PRJSZEyKm4fzjX8RofB3CHmx3brzU6p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --runTestsByPath --detectOpenHandles --forceExit --watchAll"
