[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
asset_manager = "D4QDPDykp1bEyfEnG5VbwEbQfJNjU1E2A4b3dvQkrdhZ"
balanced_dollar = "A1xSqxhcpn1KUcVJj6rJwUdWk2gWgCaUB4zuLePnKabk"
centralized_connection = "337ToYrue4zSSyS3Th3DDS6qHvFRG6JA7Zkx2zJxLXAS"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "8exXWgtzB5iyywhciSYK8uQEkmLNMaFkp4eUFHLVyvtU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize-asset-manager = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-asset-manager.ts"
initialize-balanced-dollar = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-balanced-dollar.ts"
initialize-xcall-manager = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-xcall-manager.ts"
test = "yarn run jest --runTestsByPath --detectOpenHandles --forceExit --watchAll"
