[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
asset_manager = "BAcme7CyJFs93in8YULLDNYCnxa1sD5Wq54QqLRZ5MZU"
balanced_dollar = "FMFjGpYNPfnDZAaJ2NjyADbtBxZuG4fRNmQgixq5mczE"
centralized_connection = "337ToYrue4zSSyS3Th3DDS6qHvFRG6JA7Zkx2zJxLXAS"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "FQ3G93FSqpg9nE1t8hfj7Sb5enCopR2FQXEeZ82C9R5L"
asset_manager = "BGzeVEn4LkKp8U7dhBP9SnUdYXsdkmFVjrG7awamyqWZ"
balanced_dollar = "DnTw1FNEm3TAGXPMJSpNWau1TukRCtxMW9GUzM3eJxYN"
xcall_manager = "AKgQ6MECUga4rUWRwiDkj3XZetp7eTrAhArdPBF7W3qJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize-asset-manager = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-asset-manager.ts"
initialize-balanced-dollar = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-balanced-dollar.ts"
initialize-xcall-manager = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-xcall-manager.ts"
test = "yarn run jest --runTestsByPath --detectOpenHandles --forceExit --watchAll"
