[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
asset_manager = "5G7Q2xM5qU4UWd3z4CW9YSEiVnfZmTUS1mbhSSZwTEJQ"
balanced_dollar = "Ahs9cC6PMGhasB5zUboUVNBJxAStmX1aeENDiWLz2AXH"
centralized_connection = "337ToYrue4zSSyS3Th3DDS6qHvFRG6JA7Zkx2zJxLXAS"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "4eAQxDi6UJokDysb9YMrXNJNcRChotpYory5M5ReD16i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
xcall_manager_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/axcall_manager/xcall_manager.test.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
