[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
asset_manager = "4u979CPSHUeJQbCYUAvoki4CQHDiG1257vt2DaJULPV9"
balanced_dollar = "3JfaNQh3zRyBQ3spQJJWKmgRcXuQrcNrpLH5pDvaX2gG"
centralized_connection = "337ToYrue4zSSyS3Th3DDS6qHvFRG6JA7Zkx2zJxLXAS"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "Ganbqm2tJ8SuaN6kSRWsJhXGb7aLCvHLuCySxCfkXPVL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize-asset-manager = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-asset-manager.ts"
initialize-balanced-dollar = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-balanced-dollar.ts"
initialize-xcall-manager = "yarn ts-node --project ./tsconfig.json ./scripts/initialize-xcall-manager.ts"
test = "yarn run jest --runTestsByPath --detectOpenHandles --forceExit --watchAll"
