[toolchain]

[features]
resolution = false
skip-lint = false

[programs.Localnet]
asset_manager = "8tJx9uFHvK33etttKFi8XWHEKMo3q3K6UdSWLTTKnUvX"
balanced_dollar = "7pvzYSgsMmK81xtXFCD5VQVbCZurTFxPNQ2FZHUd5rTY"
centralized_connection = "4vfkXyxMxptmREF3RaFKUwnPRuqsXJJeUFzpCjPSSVMb"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "7vfrBqZFbvfKCqVC3v7dEh8V6RV9afRu1ySuLLauCMTL"

[programs."https://solana-rpc.venture23.xyz"]
asset_manager = "8tJx9uFHvK33etttKFi8XWHEKMo3q3K6UdSWLTTKnUvX"
balanced_dollar = "7pvzYSgsMmK81xtXFCD5VQVbCZurTFxPNQ2FZHUd5rTY"
centralized_connection = "4vfkXyxMxptmREF3RaFKUwnPRuqsXJJeUFzpCjPSSVMb"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "7vfrBqZFbvfKCqVC3v7dEh8V6RV9afRu1ySuLLauCMTL"

[registry]
url = "https://solana-rpc.venture23.xyz"

[provider]
cluster = "https://solana-rpc.venture23.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --runTestsByPath --detectOpenHandles --forceExit --watchAll"
