[toolchain]

[features]
resolution = false
skip-lint = false

[programs."https://api.devnet.solana.com"]
asset_manager = "afx4C1hQjFdw7q1esUEceZiKNGdSHaudUTRAbc3HQJw"
balanced_dollar = "Bxh6sBWRvaXLqXfzh422NamVrfF63Ybrqkhi23Ho29hw"
centralized_connection = "337ToYrue4zSSyS3Th3DDS6qHvFRG6JA7Zkx2zJxLXAS"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "AtrfzxadGeoLekrfsEETYCsEhbTVLxvvoFUxDdWFfbu4"

[programs.localnet]
asset_manager = "afx4C1hQjFdw7q1esUEceZiKNGdSHaudUTRAbc3HQJw"
balanced_dollar = "FQnK1rxyPqHDpzVVrDzV4gEGHSBFQcsJ42w4926ktJCm"
centralized_connection = "337ToYrue4zSSyS3Th3DDS6qHvFRG6JA7Zkx2zJxLXAS"
xcall = "47QmEHEPSQqhpEjok5PmooeqdqBXRVpU11aRMhJGe6LW"
xcall_manager = "AtrfzxadGeoLekrfsEETYCsEhbTVLxvvoFUxDdWFfbu4"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --runTestsByPath --detectOpenHandles --forceExit --watchAll"
